/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cachoahorasi;

import java.applet.AudioClip;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pabloneitor
 */
public class DadosGen extends javax.swing.JFrame {
    private int obj;
    Cubilete objDado1 = new Cubilete();
    int [] dado = objDado1.cubileteLanza();
    int SiDadoT2 = 0;
    int voltea2 = 0;
    
    /**
     * Creates new form DadosGen
     */
    public DadosGen() {
        initComponents();
        //iconoDADO
        try{
            setIconImage(new ImageIcon(getClass().getResource("/masImG/Dice-32.png")).getImage());
        }catch(Exception ex){
        
        }
        //
        setTitle("CACHO-JUEGO");
        this.setLocationRelativeTo(null);
        jSegundoT.setEnabled(false);
        jVoltearD.setEnabled(false);
        //
       this.setLocationRelativeTo(null);

       /*ImageIcon fondo1 = new ImageIcon(getClass().getResource("/Pictures/fondo.png"));
       ImageIcon fondo2 = new ImageIcon(fondo1.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_DEFAULT));
       jLabel1.setIcon(fondo2);*/
       this.repaint();
       //........boton primer tiro
       jPrimerT.setOpaque(false);
       jPrimerT.setContentAreaFilled(false);
       jPrimerT.setBorderPainted(false);
       //........boton segundo tiro
       jSegundoT.setOpaque(false);
       jSegundoT.setContentAreaFilled(false);
       jSegundoT.setBorderPainted(false);
       //........boton volteo
       jVoltearD.setOpaque(false);
       jVoltearD.setContentAreaFilled(false);
       jVoltearD.setBorderPainted(false);
       //........boton puntaje
       jTerminarT.setOpaque(false);
       jTerminarT.setContentAreaFilled(false);
       jTerminarT.setBorderPainted(false);
       /*........boton primer casa
       jSalir.setOpaque(false);
       jSalir.setContentAreaFilled(false);
       jSalir.setBorderPainted(false);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPrimerT = new javax.swing.JButton();
        jSegundoT = new javax.swing.JButton();
        jVoltearD = new javax.swing.JButton();
        jTerminarT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckDado1 = new javax.swing.JCheckBox();
        jCheckDado2 = new javax.swing.JCheckBox();
        jCheckDado3 = new javax.swing.JCheckBox();
        jCheckDado4 = new javax.swing.JCheckBox();
        jCheckDado5 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(610, 440));
        getContentPane().setLayout(null);

        jPrimerT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-1-50.png"))); // NOI18N
        jPrimerT.setText("Tiro 1");
        jPrimerT.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Private 2-50.png"))); // NOI18N
        jPrimerT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPrimerT.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Spinner marco 3-26.png"))); // NOI18N
        jPrimerT.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-1 Filled-50.png"))); // NOI18N
        jPrimerT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPrimerT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPrimerTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPrimerTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPrimerTMousePressed(evt);
            }
        });
        jPrimerT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrimerTActionPerformed(evt);
            }
        });
        getContentPane().add(jPrimerT);
        jPrimerT.setBounds(21, 47, 71, 67);

        jSegundoT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-2-50.png"))); // NOI18N
        jSegundoT.setText("Tiro 2");
        jSegundoT.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Private 2-50.png"))); // NOI18N
        jSegundoT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jSegundoT.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Spinner marco 3-26.png"))); // NOI18N
        jSegundoT.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-2 Filled-50.png"))); // NOI18N
        jSegundoT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jSegundoT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSegundoTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSegundoTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSegundoTMousePressed(evt);
            }
        });
        jSegundoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSegundoTActionPerformed(evt);
            }
        });
        getContentPane().add(jSegundoT);
        jSegundoT.setBounds(21, 132, 71, 70);

        jVoltearD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Cambiar-50.png"))); // NOI18N
        jVoltearD.setText("VoltearD");
        jVoltearD.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Private 2-50.png"))); // NOI18N
        jVoltearD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jVoltearD.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Spinner marco 3-26.png"))); // NOI18N
        jVoltearD.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Cambiar Filled-50.png"))); // NOI18N
        jVoltearD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jVoltearD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jVoltearDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jVoltearDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jVoltearDMousePressed(evt);
            }
        });
        jVoltearD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltearDActionPerformed(evt);
            }
        });
        getContentPane().add(jVoltearD);
        jVoltearD.setBounds(21, 239, 82, 69);

        jTerminarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Lista de verificación-50.png"))); // NOI18N
        jTerminarT.setText("Puntaje");
        jTerminarT.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Private 2-50.png"))); // NOI18N
        jTerminarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTerminarT.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Spinner marco 3-26.png"))); // NOI18N
        jTerminarT.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Lista de verificación Filled-50.png"))); // NOI18N
        jTerminarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTerminarT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTerminarTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTerminarTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTerminarTMousePressed(evt);
            }
        });
        jTerminarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTerminarTActionPerformed(evt);
            }
        });
        getContentPane().add(jTerminarT);
        jTerminarT.setBounds(168, 310, 84, 79);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(175, 118, 77, 15);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 118, 73, 15);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("0");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(473, 118, 74, 15);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(263, 239, 78, 15);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("0");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(406, 239, 75, 15);

        jCheckDado1.setText("jCheckBox1");
        jCheckDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dados-01.gif"))); // NOI18N
        jCheckDado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDado1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckDado1);
        jCheckDado1.setBounds(175, 47, 77, 70);

        jCheckDado2.setText("jCheckBox2");
        jCheckDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dados-02.gif"))); // NOI18N
        jCheckDado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDado2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckDado2);
        jCheckDado2.setBounds(320, 47, 73, 70);

        jCheckDado3.setText("jCheckBox3");
        jCheckDado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dados-03.gif"))); // NOI18N
        jCheckDado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDado3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckDado3);
        jCheckDado3.setBounds(473, 47, 74, 70);

        jCheckDado4.setText("jCheckBox4");
        jCheckDado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dados-04.gif"))); // NOI18N
        jCheckDado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDado4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckDado4);
        jCheckDado4.setBounds(263, 151, 78, 70);

        jCheckDado5.setText("jCheckBox5");
        jCheckDado5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dados-05.gif"))); // NOI18N
        jCheckDado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDado5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckDado5);
        jCheckDado5.setBounds(406, 151, 75, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/fondo-2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   //Primer Tiro       
    private void jPrimerTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrimerTActionPerformed
        //dado1
        jLabel1.setText(""+dado[0]);
        imagenesResult objImag1 = new imagenesResult();
        jCheckDado1.setIcon(objImag1.Imaen(dado[0]));
        //dado2
        jLabel2.setText(""+dado[1]);
        imagenesResult objImag2 = new imagenesResult();
        jCheckDado2.setIcon(objImag2.Imaen(dado[1]));
        //dado3
        jLabel3.setText(""+dado[2]);
        imagenesResult objImag3 = new imagenesResult();
        jCheckDado3.setIcon(objImag3.Imaen(dado[2]));
        //dado4
        jLabel4.setText(""+dado[3]);
        imagenesResult objImag4 = new imagenesResult();
        jCheckDado4.setIcon(objImag4.Imaen(dado[3]));
        //dado5
        jLabel5.setText(""+dado[4]);
        imagenesResult objImag5 = new imagenesResult();
        jCheckDado5.setIcon(objImag5.Imaen(dado[4]));
        
        JOptionPane.showMessageDialog(this,"Seleccione Dados Para Segundo Tiro");
        
        jPrimerT.setEnabled(false);
        jSegundoT.setEnabled(true);
        //jSegundoT.setEnabled(false);
    }//GEN-LAST:event_jPrimerTActionPerformed
    //Segundo Tiro
    private void jSegundoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSegundoTActionPerformed
        
        //Dado_1
        if(jCheckDado1.isSelected()){
            
            dado[0] = objDado1.lanzarDado();
            jLabel1.setText(""+dado[0]);
            imagenesResult objImag1 = new imagenesResult();
            jCheckDado1.setIcon(objImag1.Imaen(dado[0]));
            jVoltearD.setEnabled(true);
            SiDadoT2++;
        }
        //Dado_2
        if(jCheckDado2.isSelected()){
            
            dado[1] = objDado1.lanzarDado();
            jLabel2.setText(""+dado[1]);
            imagenesResult objImag2 = new imagenesResult();
            jCheckDado2.setIcon(objImag2.Imaen(dado[1]));
            jVoltearD.setEnabled(true);
            SiDadoT2++;
        }
        //Dado_3
        if(jCheckDado3.isSelected()){
            dado[2] = objDado1.lanzarDado();
            jLabel3.setText(""+dado[2]);
            imagenesResult objImag3 = new imagenesResult();
            jCheckDado3.setIcon(objImag3.Imaen(dado[2]));
            jVoltearD.setEnabled(true);
            SiDadoT2++;
        }
        //Dado_4
        if(jCheckDado4.isSelected()){
            dado[3] = objDado1.lanzarDado();
            jLabel4.setText(""+dado[3]);
            imagenesResult objImag4 = new imagenesResult();
            jCheckDado4.setIcon(objImag4.Imaen(dado[3]));
            jVoltearD.setEnabled(true);
            SiDadoT2++;
        }
        //Dado_5
        if(jCheckDado5.isSelected()){
            dado[4] = objDado1.lanzarDado();
            jLabel5.setText(""+dado[4]);
            imagenesResult objImag5 = new imagenesResult();
            jCheckDado5.setIcon(objImag5.Imaen(dado[4]));
            jVoltearD.setEnabled(true);
            SiDadoT2++;
        }
        if(SiDadoT2 != 0){
            jVoltearD.setEnabled(true);
            jSegundoT.setEnabled(false);
            JOptionPane.showMessageDialog(this,"Seleccione Dados A Voltear");
        }else{
            JOptionPane.showMessageDialog(this,"Seleccione un dado o presione resultado");
            //jVoltearD.setEnabled(false);
        }
        jCheckDado1.setSelected(false);
        jCheckDado2.setSelected(false);
        jCheckDado3.setSelected(false);
        jCheckDado4.setSelected(false);
        jCheckDado5.setSelected(false);
        
        //JOptionPane.showMessageDialog(this,"Seleccione Dados A Voltear");
        
        //jSegundoT.setEnabled(false);
        jTerminarT.setEnabled(false);
    }//GEN-LAST:event_jSegundoTActionPerformed
    //Voltear Dado(s)
    private void jVoltearDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltearDActionPerformed
       
           //Dado_1
            if(jCheckDado1.isSelected()){
                /*dado[0] = objDado1.voltearDado(dado[0]);
                jLabel1.setText(""+dado[0]);
                imagenesResult objImag1 = new imagenesResult();
                jCheckDado1.setIcon(objImag1.Imaen(dado[0]));*/
                voltea2++;
                
            }
            //Dado_2
            if(jCheckDado2.isSelected()){
                /*dado[1] = objDado1.voltearDado(dado[1]);
                jLabel2.setText(""+dado[1]);
                imagenesResult objImag2 = new imagenesResult();
                jCheckDado2.setIcon(objImag2.Imaen(dado[1]));*/
                voltea2++;
                
            }
            //Dado_3
            if(jCheckDado3.isSelected()){
                /*dado[2] = objDado1.voltearDado(dado[2]);
                jLabel3.setText(""+dado[2]);
                imagenesResult objImag3 = new imagenesResult();
                jCheckDado3.setIcon(objImag3.Imaen(dado[2]));*/
                voltea2++;
            }
            //Dado_4
            if(jCheckDado4.isSelected()){
                /*dado[3] = objDado1.voltearDado(dado[3]);
                jLabel4.setText(""+dado[3]);
                imagenesResult objImag4 = new imagenesResult();
                jCheckDado4.setIcon(objImag4.Imaen(dado[3]));*/
                voltea2++;
                
            }
            //Dado_5
            if(jCheckDado5.isSelected()){
                /*dado[4] = objDado1.voltearDado(dado[4]);
                jLabel5.setText(""+dado[4]);
                imagenesResult objImag5 = new imagenesResult();
                jCheckDado5.setIcon(objImag5.Imaen(dado[4]));*/
                voltea2++;
            }
        if(voltea2 == 1 || voltea2 == 2){
            //
            jVoltearD.setEnabled(false);
            //jSegundoT.setEnabled(false);
            JOptionPane.showMessageDialog(this,"Presione terminar");
            //Dado_1
            if(jCheckDado1.isSelected()){
                dado[0] = objDado1.voltearDado(dado[0]);
                jLabel1.setText(""+dado[0]);
                imagenesResult objImag1 = new imagenesResult();
                jCheckDado1.setIcon(objImag1.Imaen(dado[0]));
                //voltea2++;
                
            }
            //Dado_2
            if(jCheckDado2.isSelected()){
                dado[1] = objDado1.voltearDado(dado[1]);
                jLabel2.setText(""+dado[1]);
                imagenesResult objImag2 = new imagenesResult();
                jCheckDado2.setIcon(objImag2.Imaen(dado[1]));
                //voltea2++;
                
            }
            //Dado_3
            if(jCheckDado3.isSelected()){
                dado[2] = objDado1.voltearDado(dado[2]);
                jLabel3.setText(""+dado[2]);
                imagenesResult objImag3 = new imagenesResult();
                jCheckDado3.setIcon(objImag3.Imaen(dado[2]));
                //voltea2++;
            }
            //Dado_4
            if(jCheckDado4.isSelected()){
                dado[3] = objDado1.voltearDado(dado[3]);
                jLabel4.setText(""+dado[3]);
                imagenesResult objImag4 = new imagenesResult();
                jCheckDado4.setIcon(objImag4.Imaen(dado[3]));
                //voltea2++;
                
            }
            //Dado_5
            if(jCheckDado5.isSelected()){
                dado[4] = objDado1.voltearDado(dado[4]);
                jLabel5.setText(""+dado[4]);
                imagenesResult objImag5 = new imagenesResult();
                jCheckDado5.setIcon(objImag5.Imaen(dado[4]));
                //voltea2++;
            }
            jTerminarT.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this,"Seleccione solo uno o dos dados a voltear");
            //jVoltearD.setEnabled(false);
             //Dado_1
            if(jCheckDado1.isSelected()){
                imagenesResult objImag1 = new imagenesResult();
                jCheckDado1.setIcon(objImag1.Imaen(dado[0]));
                
            }
            //Dado_2
            if(jCheckDado2.isSelected()){
                
                imagenesResult objImag2 = new imagenesResult();
                jCheckDado2.setIcon(objImag2.Imaen(dado[1]));
                
            }
            //Dado_3
            if(jCheckDado3.isSelected()){
                
                imagenesResult objImag3 = new imagenesResult();
                jCheckDado3.setIcon(objImag3.Imaen(dado[2]));
            }
            //Dado_4
            if(jCheckDado4.isSelected()){
                
                imagenesResult objImag4 = new imagenesResult();
                jCheckDado4.setIcon(objImag4.Imaen(dado[3]));
                
            }
            //Dado_5
            if(jCheckDado5.isSelected()){
                
                imagenesResult objImag5 = new imagenesResult();
                jCheckDado5.setIcon(objImag5.Imaen(dado[4]));
            }
            //
            jCheckDado1.setSelected(false);
            jCheckDado2.setSelected(false);
            jCheckDado3.setSelected(false);
            jCheckDado4.setSelected(false);
            jCheckDado5.setSelected(false);
            voltea2 = 0;
        }
        
        
        
    }//GEN-LAST:event_jVoltearDActionPerformed
    //metodo de ordenamiento
    private void ordenarDados(int[] dado){
        for(int i = 0; i < dado.length - 1; i++){
            for(int j = 0; j < dado.length - 1; j++){
                if (dado[j] > dado[j + 1]){
                    int tmp = dado[j+1];
                    dado[j+1] = dado[j];
                    dado[j] = tmp;
                    
                }
            }
            
        }
        for(int i = 0; i < 5; i++){
            System.out.println("dadonN: " + dado[i]);
        }
        
    }
    //esGrande?
    private boolean esGrand(int[] dado){
        boolean res = false;
        int y = 0;
        int x = 0;
        int a = 0;
        int m;
        int n = dado[0];
        x = buscarRep(dado,n);
        while(dado[a] == dado[0]){
            a++;
        }
        m = dado[a];
        y = buscarRep(dado,m);   
        if(x == 0 && y == 5 || x == 5 && y == 0){
            res = true;
        }
        return res;
        
        //
    }
    //esEscalera?
    private boolean esEsca(int[] dado){
        boolean res = false;
        if(dado[0] ==1 && dado[1] ==3 && dado[2] ==4  && dado[3] ==5 && dado[4] ==6){
            res = true;
        }
        if(dado[0] ==1 && dado[1] ==2 && dado[2] ==3  && dado[3] ==4 && dado[4] ==5){
            res = true;
        }
        if(dado[0] ==2 && dado[1] ==3 && dado[2] ==4  && dado[3] ==5 && dado[4] ==6){
            res = true;
        }
        
        return res;
    }
    
    //
    //esFull?
    private boolean esFull(int[] dado){
        boolean res = false;
        int y = 0;
        int x = 0;
        int a = 0;
        int m;
        int n = dado[0];
        x = buscarRep(dado,n);
        while(dado[a] == dado[0]){
            a++;
        }
        m = dado[a];
        y = buscarRep(dado,m);   
        if(x == 2 && y == 3 || x == 3 && y == 2){
            res = true;
        }
        return res;
        
        //

    }
    //esPoker??
    private boolean esPok(int[] dado){
        boolean res = false;
            int y = 0;
            int x = 0;
            int a = 0;
            int m;
            int n = dado[0];
            x = buscarRep(dado,n);
            while(dado[a] == dado[0]){
                a++;
            }
            m = dado[a];
            y = buscarRep(dado,m);
            if(x==1 && y==4 || x==4 && y==1){
                res = true;
            }
            return res;
    }
    //
    private boolean esGrande(int[] dado){
        boolean res = false;
        int cont = buscarRep(dado,dado[0]);
        if(cont == 5)
            res = true;
        return res;
    }
    
    private int buscarRep(int[] dado,int n){
        int cont = 0;
        for(int j = 0;j < dado.length;j++){
            if(n == dado[j]){
                cont++;
            }
        }
        if(cont == 0)
            cont++;
        return cont;
    }
    //
    //
    public boolean iguales(int[] a,int[] b){
        boolean res = true;
        for(int i = 0;i < a.length;i++){
            if(a[i] != b[i]){
                res = false;
                i = a.length;
            }
        }
        return res;
    }
    //
    //Terminar Turno
    private void jTerminarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTerminarTActionPerformed
        int b = 0; 
        int t = 0;
        int tr = 0;
        int c = 0;
        int q = 0;
        int se = 0;
        int es = 0;
        int full = 0;
        int pok = 0;
        int gr = 0;
        int gr2 = 0;
        ordenarDados(dado);
        for(int i = 0;i < dado.length;i++){
            //balas -> senas
            switch (dado[i]) {
                case 1:
                    //balas
                    b = b + dado[i];
                    break;
                case 2:
                    //tontos
                    t = t + dado[i];
                    break;
                case 3:
                    //trenes
                    tr = tr + dado[i];
                    break;
                case 4:
                    //cuadras
                    c = c + dado[i];
                    break;
                case 5:
                    //quinas
                    q = q + dado[i];
                    break;
                case 6:
                    //senas
                    se = se + dado[i];
                    break;   
            }
            //grande
            int plus = 5;
            if(!jVoltearD.isEnabled()&&jSegundoT.isEnabled()){
                if(esGrande(dado)){
                    gr = 50 + plus;
                }else{
                    if(esEsca(dado)){
                        es = 20 + plus;
                    }
                    if(esFull(dado)){
                        full = 30 + plus;
                    }
                    if(esPok(dado)){
                        pok = 40 + plus;
                    }
                }
            }else{
                if(esGrande(dado)){
                    gr = 50;
                }else{
                    if(esEsca(dado)){
                        es = 20;
                    }
                    if(esFull(dado)){
                        full = 30;
                    }
                    if(esPok(dado)){
                        pok = 40;
                    }
                }
            }
        /*//esDormida
        if(dado[0]==dado[i+1]){
            JOptionPane.showMessageDialog(this,"DORMIDA");
        }*/
        
        }
        
        
        System.out.println("puntaje de balas: "+ b);
        System.out.println("puntaje de tontos: "+ t);
        System.out.println("puntaje de trenes: "+ tr);
        System.out.println("puntaje de cuadras: "+ c);
        System.out.println("puntaje de quinas: "+ q);
        System.out.println("puntaje de senas: "+ se);
        System.out.println("puntaje de grandes: "+ gr);
        System.out.println("puntaje de grandes: "+ gr2);
        System.out.println("puntaje de escalera: "+ es);
        System.out.println("puntaje de full: "+ full);
        System.out.println("puntaje de poker: "+ pok);
        
        puntajeT puntaje = new puntajeT();
        puntaje.setVisible(true);
        puntajeT.jLabel1.setText(Integer.toString(b));
        puntajeT.jLabel2.setText(Integer.toString(t));
        puntajeT.jLabel3.setText(Integer.toString(tr));
        puntajeT.jLabel4.setText(Integer.toString(c));
        puntajeT.jLabel5.setText(Integer.toString(q));
        puntajeT.jLabel6.setText(Integer.toString(se));
        puntajeT.jLabel10.setText(Integer.toString(gr));
        puntajeT.jLabel11.setText(Integer.toString(gr2));
        puntajeT.jLabel7.setText(Integer.toString(es));
        puntajeT.jLabel9.setText(Integer.toString(full));
        puntajeT.jLabel8.setText(Integer.toString(pok));
        dispose();
        
    }//GEN-LAST:event_jTerminarTActionPerformed

    private void jCheckDado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDado1ActionPerformed
        if(jCheckDado1.isSelected()){
            //jSegundoT.setEnabled(true);
            imagenes1 objImag1 = new imagenes1();
            jCheckDado1.setIcon(objImag1.gifDado1(dado[0]));
            
        }/*else{
            
        }*/
    }//GEN-LAST:event_jCheckDado1ActionPerformed

    private void jCheckDado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDado2ActionPerformed
        if(jCheckDado2.isSelected()){
            //jSegundoT.setEnabled(true);
            imagenes1 objImag1 = new imagenes1();
            jCheckDado2.setIcon(objImag1.gifDado1(dado[1]));
        }/*else{
            jSegundoT.setEnabled(false);
        }*/
    }//GEN-LAST:event_jCheckDado2ActionPerformed

    private void jCheckDado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDado3ActionPerformed
        if(jCheckDado3.isSelected()){
            imagenes1 objImag1 = new imagenes1();
            jCheckDado3.setIcon(objImag1.gifDado1(dado[2]));
        }
    }//GEN-LAST:event_jCheckDado3ActionPerformed

    private void jCheckDado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDado4ActionPerformed
        if(jCheckDado4.isSelected()){
            imagenes1 objImag1 = new imagenes1();
            jCheckDado4.setIcon(objImag1.gifDado1(dado[3]));
        }
    }//GEN-LAST:event_jCheckDado4ActionPerformed

    private void jCheckDado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDado5ActionPerformed
        if(jCheckDado5.isSelected()){
            imagenes1 objImag1 = new imagenes1();
            jCheckDado5.setIcon(objImag1.gifDado1(dado[4]));
        }
    }//GEN-LAST:event_jCheckDado5ActionPerformed
    //sonido boton primerT
    private void jPrimerTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrimerTMouseEntered
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jPrimerTMouseEntered

    private void jPrimerTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrimerTMouseExited
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jPrimerTMouseExited

    private void jPrimerTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrimerTMousePressed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/clicked.wav"));
        sonido.play();
    }//GEN-LAST:event_jPrimerTMousePressed
    //sonido boton segundoT
    private void jSegundoTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSegundoTMouseEntered
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jSegundoTMouseEntered

    private void jSegundoTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSegundoTMouseExited
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jSegundoTMouseExited

    private void jSegundoTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSegundoTMousePressed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/clicked.wav"));
        sonido.play();
    }//GEN-LAST:event_jSegundoTMousePressed
    //sonido boton voltearD
    private void jVoltearDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVoltearDMouseEntered
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jVoltearDMouseEntered

    private void jVoltearDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVoltearDMouseExited
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jVoltearDMouseExited

    private void jVoltearDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVoltearDMousePressed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/clicked.wav"));
        sonido.play();
    }//GEN-LAST:event_jVoltearDMousePressed
    //sonido boton TerminarT
    private void jTerminarTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTerminarTMouseEntered
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jTerminarTMouseEntered

    private void jTerminarTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTerminarTMouseExited
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jTerminarTMouseExited

    private void jTerminarTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTerminarTMousePressed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/clicked.wav"));
        sonido.play();
    }//GEN-LAST:event_jTerminarTMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosGen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckDado1;
    private javax.swing.JCheckBox jCheckDado2;
    private javax.swing.JCheckBox jCheckDado3;
    private javax.swing.JCheckBox jCheckDado4;
    private javax.swing.JCheckBox jCheckDado5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jPrimerT;
    private javax.swing.JButton jSegundoT;
    private javax.swing.JButton jTerminarT;
    private javax.swing.JButton jVoltearD;
    // End of variables declaration//GEN-END:variables
}
