/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cachoahorasi;

import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author DELL
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        // setIconImage(new ImageIcon(getClass().getResource("../Imagenes/Póker-de-dados.jpg")).getImage());
       this.setLocationRelativeTo(null);

       ImageIcon fondo1 = new ImageIcon(getClass().getResource("/Pictures/fondo.png"));
       ImageIcon fondo2 = new ImageIcon(fondo1.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_DEFAULT));
       jLabel1.setIcon(fondo2);
       this.repaint();
       //........boton jugar
       jButtonJugar.setOpaque(false);
       jButtonJugar.setContentAreaFilled(false);
       jButtonJugar.setBorderPainted(false);
       //........boton reglas
       jButtonReglas.setOpaque(false);
       jButtonReglas.setContentAreaFilled(false);
       jButtonReglas.setBorderPainted(false);
       //........boton creditos
       jButtonCreditos.setOpaque(false);
       jButtonCreditos.setContentAreaFilled(false);
       jButtonCreditos.setBorderPainted(false);
       //........boton salir
       jButtonSalir.setOpaque(false);
       jButtonSalir.setContentAreaFilled(false);
       jButtonSalir.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonJugar = new javax.swing.JButton();
        jButtonReglas = new javax.swing.JButton();
        jButtonCreditos = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 440));
        getContentPane().setLayout(null);

        jButtonJugar.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Reproducir en círculo-50.png")); // NOI18N
        jButtonJugar.setText("Jugar");
        jButtonJugar.setToolTipText("");
        jButtonJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonJugar.setPreferredSize(new java.awt.Dimension(85, 80));
        jButtonJugar.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Reproducir en círculo-50 (1).png")); // NOI18N
        jButtonJugar.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Reproducir en círculo Filled-50.png")); // NOI18N
        jButtonJugar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJugar);
        jButtonJugar.setBounds(60, 280, 90, 80);

        jButtonReglas.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Información-50.png")); // NOI18N
        jButtonReglas.setText("Reglas");
        jButtonReglas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReglas.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Información-50 (1).png")); // NOI18N
        jButtonReglas.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Información Filled-50.png")); // NOI18N
        jButtonReglas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReglasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReglas);
        jButtonReglas.setBounds(190, 280, 90, 80);

        jButtonCreditos.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Para expertos-50.png")); // NOI18N
        jButtonCreditos.setText("Creditos");
        jButtonCreditos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCreditos.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Para expertos-50 (1).png")); // NOI18N
        jButtonCreditos.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Para expertos Filled-50.png")); // NOI18N
        jButtonCreditos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCreditos);
        jButtonCreditos.setBounds(320, 280, 90, 80);

        jButtonSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Señal de salida-50.png")); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir.setMaximumSize(new java.awt.Dimension(85, 80));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(85, 80));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(85, 80));
        jButtonSalir.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Señal de salida Filled-50.png")); // NOI18N
        jButtonSalir.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\icons8-Salida Filled-50.png")); // NOI18N
        jButtonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir);
        jButtonSalir.setBounds(450, 280, 90, 80);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        MainUser game = new MainUser();
        game.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreditosActionPerformed
        /*Creditos credits = new Creditos();
        credits.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_jButtonCreditosActionPerformed

    private void jButtonReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReglasActionPerformed
        Reglas rules = new Reglas();
        rules.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReglasActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreditos;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonReglas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
