/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cachoahorasi;

import java.applet.AudioClip;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author DELL
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        // setIconImage(new ImageIcon(getClass().getResource("../Imagenes/Póker-de-dados.jpg")).getImage());
       this.setLocationRelativeTo(null);

       ImageIcon fondo1 = new ImageIcon(getClass().getResource("/Pictures/fondos-geometricos-L-j8PlAC.jpg"));
       ImageIcon fondo2 = new ImageIcon(fondo1.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_DEFAULT));
       jLabel1.setIcon(fondo2);
       this.repaint();
       //........boton jugar
       jButtonJugar.setOpaque(false);
       jButtonJugar.setContentAreaFilled(false);
       jButtonJugar.setBorderPainted(false);
       //........boton reglas
       jButtonReglas.setOpaque(false);
       jButtonReglas.setContentAreaFilled(false);
       jButtonReglas.setBorderPainted(false);
       //........boton creditos
       jButtonCreditos.setOpaque(false);
       jButtonCreditos.setContentAreaFilled(false);
       jButtonCreditos.setBorderPainted(false);
       //........boton salir
       jButtonSalir.setOpaque(false);
       jButtonSalir.setContentAreaFilled(false);
       jButtonSalir.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonJugar = new javax.swing.JButton();
        jButtonReglas = new javax.swing.JButton();
        jButtonCreditos = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 440));
        getContentPane().setLayout(null);

        jButtonJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Reproducir en círculo-50.png"))); // NOI18N
        jButtonJugar.setText("Jugar");
        jButtonJugar.setToolTipText("");
        jButtonJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonJugar.setPreferredSize(new java.awt.Dimension(85, 80));
        jButtonJugar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Spinner marco 3-26.png"))); // NOI18N
        jButtonJugar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Reproducir en círculo Filled-50.png"))); // NOI18N
        jButtonJugar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonJugarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonJugarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonJugarMousePressed(evt);
            }
        });
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJugar);
        jButtonJugar.setBounds(60, 280, 90, 80);

        jButtonReglas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Información-50.png"))); // NOI18N
        jButtonReglas.setText("Reglas");
        jButtonReglas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReglas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Spinner marco 3-26.png"))); // NOI18N
        jButtonReglas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Información Filled-50.png"))); // NOI18N
        jButtonReglas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonReglas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonReglasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonReglasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonReglasMousePressed(evt);
            }
        });
        jButtonReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReglasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReglas);
        jButtonReglas.setBounds(190, 280, 90, 80);

        jButtonCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Para expertos-50 (1).png"))); // NOI18N
        jButtonCreditos.setText("Creditos");
        jButtonCreditos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCreditos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Spinner marco 3-26.png"))); // NOI18N
        jButtonCreditos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Para expertos Filled-50.png"))); // NOI18N
        jButtonCreditos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCreditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCreditosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonCreditosMousePressed(evt);
            }
        });
        jButtonCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCreditos);
        jButtonCreditos.setBounds(320, 280, 90, 80);

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Señal de salida-50.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir.setMaximumSize(new java.awt.Dimension(85, 80));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(85, 80));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(85, 80));
        jButtonSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Salida Filled-50.png"))); // NOI18N
        jButtonSalir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-Señal de salida Filled-50.png"))); // NOI18N
        jButtonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonSalirMousePressed(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir);
        jButtonSalir.setBounds(450, 280, 90, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/cooltext249515936388735.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 80, 290, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/DADopng-iloveimg-resized.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 170, 150);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/fondos-geometricos-L-j8PlAC.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        MainUser game = new MainUser();
        game.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreditosActionPerformed
        Creditos credits = new Creditos();
        credits.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCreditosActionPerformed

    private void jButtonReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReglasActionPerformed
        Reglas rules = new Reglas();
        rules.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReglasActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed
    //sonido boton jugar
    private void jButtonJugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJugarMouseEntered
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonJugarMouseEntered

    private void jButtonJugarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJugarMouseExited
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonJugarMouseExited

    private void jButtonJugarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJugarMousePressed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/clicked.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonJugarMousePressed
    //boton informacion
    private void jButtonReglasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReglasMousePressed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/clicked.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonReglasMousePressed

    private void jButtonReglasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReglasMouseEntered
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonReglasMouseEntered

    private void jButtonReglasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReglasMouseExited
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonReglasMouseExited
    //boton creditos
    private void jButtonCreditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreditosMouseEntered
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonCreditosMouseEntered

    private void jButtonCreditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreditosMouseExited
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonCreditosMouseExited

    private void jButtonCreditosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreditosMousePressed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/clicked.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonCreditosMousePressed
    //boton salir
    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonSalirMouseEntered

    private void jButtonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseExited
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/selected.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonSalirMouseExited

    private void jButtonSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMousePressed
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonido/clicked.wav"));
        sonido.play();
    }//GEN-LAST:event_jButtonSalirMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreditos;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonReglas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
