/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cachoahorasi;

import javax.swing.JOptionPane;

/**
 *
 * @author Pabloneitor
 */
public class JuegoD3 extends javax.swing.JFrame {
    static int turnP;//controla par o impar en turnojugador
    static int turnoS = 3;//controla el turno actual
    static int turno = 0;//turno actual inicio
    /**
     * Creates new form JuegoD3
     */
    public JuegoD3() {
        initComponents();
        this.setLocationRelativeTo(null);
        //
        /*ImageIcon fondo1 = new ImageIcon(getClass().getResource("/Pictures/fondo.png"));
       ImageIcon fondo2 = new ImageIcon(fondo1.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_DEFAULT));
       jLabel1.setIcon(fondo2);*/
       this.repaint();
        //
        jBjugar1.setEnabled(true);
        jBjugar2.setEnabled(false);
        jBjugar3.setEnabled(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPuntaje1 = new javax.swing.JLabel();
        jPuntajeEs = new javax.swing.JLabel();
        jPuntaje4 = new javax.swing.JLabel();
        jBjugar1 = new javax.swing.JButton();
        jBjugar2 = new javax.swing.JButton();
        jBjugar3 = new javax.swing.JButton();
        jBresultado = new javax.swing.JButton();
        jBexit = new javax.swing.JButton();
        jPuntaje2 = new javax.swing.JLabel();
        jPuntajeFull = new javax.swing.JLabel();
        jPuntaje5 = new javax.swing.JLabel();
        jPuntaje3 = new javax.swing.JLabel();
        jPuntajePoker = new javax.swing.JLabel();
        jPuntaje6 = new javax.swing.JLabel();
        jPuntajeG1 = new javax.swing.JLabel();
        jPuntajeG2 = new javax.swing.JLabel();
        jPuntaje11 = new javax.swing.JLabel();
        jPuntajeES2 = new javax.swing.JLabel();
        jPuntaje44 = new javax.swing.JLabel();
        jPuntaje22 = new javax.swing.JLabel();
        jPuntajeFull2 = new javax.swing.JLabel();
        jPuntaje55 = new javax.swing.JLabel();
        jPuntaje33 = new javax.swing.JLabel();
        jPuntajePoker2 = new javax.swing.JLabel();
        jPuntaje66 = new javax.swing.JLabel();
        jPuntajeG12 = new javax.swing.JLabel();
        jPuntajeG22 = new javax.swing.JLabel();
        jPuntajeES3 = new javax.swing.JLabel();
        jPuntaje444 = new javax.swing.JLabel();
        jPuntaje111 = new javax.swing.JLabel();
        jPuntajeFull3 = new javax.swing.JLabel();
        jPuntaje555 = new javax.swing.JLabel();
        jPuntaje222 = new javax.swing.JLabel();
        jPuntaje333 = new javax.swing.JLabel();
        jPuntajePoker3 = new javax.swing.JLabel();
        jPuntaje666 = new javax.swing.JLabel();
        jPuntajeG13 = new javax.swing.JLabel();
        jPuntajeG23 = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(660, 440));

        jLabel1.setText("Jugador_1");

        jLabel2.setText("Jugador_2");

        jLabel3.setText("Jugador_3");

        jPuntajeEs.setText("0");

        jPuntaje4.setText("0");

        jBjugar1.setText("Juega1");
        jBjugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjugar1ActionPerformed(evt);
            }
        });

        jBjugar2.setText("Juega2");
        jBjugar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjugar2ActionPerformed(evt);
            }
        });

        jBjugar3.setText("Juega3");
        jBjugar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjugar3ActionPerformed(evt);
            }
        });

        jBresultado.setText("Resultado");
        jBresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBresultadoActionPerformed(evt);
            }
        });

        jBexit.setText("Salir");
        jBexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexitActionPerformed(evt);
            }
        });

        jPuntajeFull.setText("0");

        jPuntaje5.setText("0");

        jPuntaje3.setText("0");

        jPuntajePoker.setText("0");

        jPuntaje6.setText("0");

        jPuntajeG1.setText("0");

        jPuntajeG2.setText("0");

        jPuntajeES2.setText("0");

        jPuntaje44.setText("0");

        jPuntajeFull2.setText("0");

        jPuntaje55.setText("0");

        jPuntaje33.setText("0");

        jPuntajePoker2.setText("0");

        jPuntaje66.setText("0");

        jPuntajeG12.setText("0");

        jPuntajeG22.setText("0");

        jPuntajeES3.setText("0");

        jPuntaje444.setText("0");

        jPuntajeFull3.setText("0");

        jPuntaje555.setText("0");

        jPuntaje333.setText("0");

        jPuntajePoker3.setText("0");

        jPuntaje666.setText("0");

        jPuntajeG13.setText("0");

        jPuntajeG23.setText("0");

        jButtonEdit.setText("EditarJD3");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\backgroundFinal.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel2)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jBjugar1)
                        .addGap(139, 139, 139)
                        .addComponent(jBjugar2)
                        .addGap(151, 151, 151)
                        .addComponent(jBjugar3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPuntaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPuntajeEs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jPuntaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPuntaje11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPuntajeES2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPuntaje44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jPuntaje111, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPuntajeES3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPuntaje444, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPuntaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPuntajeFull, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jPuntaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPuntaje22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPuntajeFull2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPuntaje55, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jPuntaje222, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPuntajeFull3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPuntaje555, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPuntajeG1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPuntajeG2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jPuntajeG12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPuntajeG22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jPuntajeG13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPuntajeG23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBresultado)
                                .addGap(151, 151, 151)
                                .addComponent(jButtonEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBexit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPuntaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jPuntajePoker, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jPuntaje6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jPuntaje33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPuntajePoker2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPuntaje66, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jPuntaje333, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPuntajePoker3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPuntaje666, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBjugar1)
                    .addComponent(jBjugar2)
                    .addComponent(jBjugar3))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPuntajeEs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntajeES2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntajeES3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje444, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPuntajeFull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntajeFull2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje222, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntajeFull3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje555, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuntaje22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPuntaje3)
                    .addComponent(jPuntajePoker)
                    .addComponent(jPuntaje6)
                    .addComponent(jPuntaje33)
                    .addComponent(jPuntajePoker2)
                    .addComponent(jPuntaje66)
                    .addComponent(jPuntaje333)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPuntajePoker3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPuntaje666, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPuntajeG1)
                    .addComponent(jPuntajeG2)
                    .addComponent(jPuntajeG12)
                    .addComponent(jPuntajeG22)
                    .addComponent(jPuntajeG13)
                    .addComponent(jPuntajeG23))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBresultado)
                    .addComponent(jButtonEdit)
                    .addComponent(jBexit))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBjugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjugar1ActionPerformed
        DadosGen3 juega1 = new DadosGen3();
        juega1.setVisible(true);
        turno++;
        System.out.println("turnoNro: " + turno);
        //jBjugar2.setEnabled(false);
        //jBjugar1.setEnabled(true);
        jBjugar2.setEnabled(true);
        jBjugar1.setEnabled(false);
    }//GEN-LAST:event_jBjugar1ActionPerformed

    private void jBjugar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjugar3ActionPerformed
        DadosGen3 juega1 = new DadosGen3();
        juega1.setVisible(true);
        turno++;
        System.out.println("turnoNro: " + turno);
        //jBjugar2.setEnabled(false);
        //jBjugar1.setEnabled(true);
        jBjugar1.setEnabled(true);
        jBjugar3.setEnabled(false);
    }//GEN-LAST:event_jBjugar3ActionPerformed

    private void jBjugar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjugar2ActionPerformed
        DadosGen3 juega1 = new DadosGen3();
        juega1.setVisible(true);
        turno++;
        System.out.println("turnoNro: " + turno);
        //jBjugar2.setEnabled(false);
        //jBjugar1.setEnabled(true);
        jBjugar3.setEnabled(true);
        jBjugar2.setEnabled(false);
    }//GEN-LAST:event_jBjugar2ActionPerformed

    private void jBresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBresultadoActionPerformed
        int p1 = 0;
        int p2 = 0;
        int p3 = 0;
        
        int num1 = Integer.parseInt( jPuntaje1.getText());
        int num2 = Integer.parseInt( jPuntaje2.getText());
        int num3 = Integer.parseInt( jPuntaje3.getText());
        int num4 = Integer.parseInt( jPuntaje4.getText());
        int num5 = Integer.parseInt( jPuntaje5.getText());
        int num6 = Integer.parseInt( jPuntaje6.getText());
        int numG1 = Integer.parseInt( jPuntajeG1.getText());
        int numG2 = Integer.parseInt( jPuntajeG2.getText());
        int numEs = Integer.parseInt( jPuntajeEs.getText());
        int numFull = Integer.parseInt( jPuntajePoker.getText());
        int numPok = Integer.parseInt( jPuntajeFull.getText());
        
        int num11 = Integer.parseInt( jPuntaje11.getText());
        int num22 = Integer.parseInt( jPuntaje22.getText());
        int num33 = Integer.parseInt( jPuntaje33.getText());
        int num44 = Integer.parseInt( jPuntaje44.getText());
        int num55 = Integer.parseInt( jPuntaje55.getText());
        int num66 = Integer.parseInt( jPuntaje66.getText());
        int numG12 = Integer.parseInt( jPuntajeG12.getText());
        int numG22 = Integer.parseInt( jPuntajeG22.getText());
        int numEs2 = Integer.parseInt( jPuntajeES2.getText());
        int numFull2 = Integer.parseInt( jPuntajePoker2.getText());
        int numPok2 = Integer.parseInt( jPuntajeFull2.getText());
        
        int num111 = Integer.parseInt( jPuntaje111.getText());
        int num222 = Integer.parseInt( jPuntaje222.getText());
        int num333 = Integer.parseInt( jPuntaje333.getText());
        int num444 = Integer.parseInt( jPuntaje444.getText());
        int num555 = Integer.parseInt( jPuntaje555.getText());
        int num666 = Integer.parseInt( jPuntaje666.getText());
        int numG13 = Integer.parseInt( jPuntajeG13.getText());
        int numG23 = Integer.parseInt( jPuntajeG23.getText());
        int numEs3 = Integer.parseInt( jPuntajeES3.getText());
        int numFull3 = Integer.parseInt( jPuntajePoker3.getText());
        int numPok3 = Integer.parseInt( jPuntajePoker3.getText());
        
        p1 = num1 + num2 + num3 + num4 + num5 + num6 + numG1 +numG2 + numEs + numFull + numPok;
        p2 = num11 + num22 + num33 + num44 + num55 + num66 + numG12 + numG22 + numEs2 + numFull2 + numPok2;
        p3 = num111 + num222 + num333 + num444 + num555 + num666 + numG13 + numG23 + numEs3 + numFull3 + numPok3;
        
        System.out.println(p1);
        System.out.println(p2);
        System.out.println(p3);
        
        if(p1>p2 && p1>p3){
            JOptionPane.showMessageDialog(this,
                "Puntaje Jugador 1:" + p1 + 
                "\nPuntaje Jugador 2:" + p2+
                "\nPuntaje Jugador 3:" + p3+
                "\n\nJugador 1 Gano");
        }else if(p2>p1 && p2>p3){
            JOptionPane.showMessageDialog(this,
                "Puntaje Jugador 1:" + p1 + 
                "\nPuntaje Jugador 2:" + p2+
                "\nPuntaje Jugador 3:" + p3+
                "\n\nJugador 2 Gano");
        }else if(p2>p1 && p2>p3){
            JOptionPane.showMessageDialog(this,
                "Puntaje Jugador 1:" + p1 + 
                "\nPuntaje Jugador 2:" + p2+
                "\nPuntaje Jugador 3:" + p3+
                "\n\nJugador 2 Gano");
        }else if(p1== p2 && p2 == p3){
            JOptionPane.showMessageDialog(this,
                "Puntaje Jugador 1:" + p1 + 
                "\nPuntaje Jugador 2:" + p2+
                "\n\nEmpate");
        }
    }//GEN-LAST:event_jBresultadoActionPerformed

    private void jBexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexitActionPerformed
        MainUser game = new MainUser();
        game.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBexitActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoD3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBexit;
    private javax.swing.JButton jBjugar1;
    private javax.swing.JButton jBjugar2;
    private javax.swing.JButton jBjugar3;
    private javax.swing.JButton jBresultado;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jPuntaje1;
    public static javax.swing.JLabel jPuntaje11;
    public static javax.swing.JLabel jPuntaje111;
    public static javax.swing.JLabel jPuntaje2;
    public static javax.swing.JLabel jPuntaje22;
    public static javax.swing.JLabel jPuntaje222;
    public static javax.swing.JLabel jPuntaje3;
    public static javax.swing.JLabel jPuntaje33;
    public static javax.swing.JLabel jPuntaje333;
    public static javax.swing.JLabel jPuntaje4;
    public static javax.swing.JLabel jPuntaje44;
    public static javax.swing.JLabel jPuntaje444;
    public static javax.swing.JLabel jPuntaje5;
    public static javax.swing.JLabel jPuntaje55;
    public static javax.swing.JLabel jPuntaje555;
    public static javax.swing.JLabel jPuntaje6;
    public static javax.swing.JLabel jPuntaje66;
    public static javax.swing.JLabel jPuntaje666;
    public static javax.swing.JLabel jPuntajeES2;
    public static javax.swing.JLabel jPuntajeES3;
    public static javax.swing.JLabel jPuntajeEs;
    public static javax.swing.JLabel jPuntajeFull;
    public static javax.swing.JLabel jPuntajeFull2;
    public static javax.swing.JLabel jPuntajeFull3;
    public static javax.swing.JLabel jPuntajeG1;
    public static javax.swing.JLabel jPuntajeG12;
    public static javax.swing.JLabel jPuntajeG13;
    public static javax.swing.JLabel jPuntajeG2;
    public static javax.swing.JLabel jPuntajeG22;
    public static javax.swing.JLabel jPuntajeG23;
    public static javax.swing.JLabel jPuntajePoker;
    public static javax.swing.JLabel jPuntajePoker2;
    public static javax.swing.JLabel jPuntajePoker3;
    // End of variables declaration//GEN-END:variables
}
