/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cachoahorasi;

import static cachoahorasi.juega1vs1.jBjugar2;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.lang.*;

/**
 *
 * @author pabloneitor
 */
public class puntajeT extends javax.swing.JFrame {
       
    /**
     * Creates new form puntajeT
     */
    public puntajeT() {
        initComponents();
        this.setLocationRelativeTo(null);
        buttonGroup1.add(jRadioButtonBala);
        buttonGroup1.add(jRadioButtonTonto);
        buttonGroup1.add(jRadioButtonTren);
        buttonGroup1.add(jRadioButtonCuadra);
        buttonGroup1.add(jRadioButtonQuina);
        buttonGroup1.add(jRadioButtonSena);
        buttonGroup1.add(jRadioButtonGrnd1);
        buttonGroup1.add(jRadioButtonEsca);
        buttonGroup1.add(jRadioButtonPoker);
        buttonGroup1.add(jRadioButtonFull);
        buttonGroup1.add(jRadioButtonGrnd2);
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonBala = new javax.swing.JRadioButton();
        jRadioButtonTonto = new javax.swing.JRadioButton();
        jRadioButtonTren = new javax.swing.JRadioButton();
        jRadioButtonCuadra = new javax.swing.JRadioButton();
        jRadioButtonQuina = new javax.swing.JRadioButton();
        jRadioButtonSena = new javax.swing.JRadioButton();
        jRadioButtonGrnd1 = new javax.swing.JRadioButton();
        jButtonSave = new javax.swing.JButton();
        jRadioButtonEsca = new javax.swing.JRadioButton();
        jRadioButtonPoker = new javax.swing.JRadioButton();
        jRadioButtonFull = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButtonGrnd2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButtonBala.setText("Puntaje Balas:");

        jRadioButtonTonto.setText("Puntaje Tontos:");

        jRadioButtonTren.setText("Puntaje Trenes:");

        jRadioButtonCuadra.setText("Puntaje Cuadras:");

        jRadioButtonQuina.setText("Puntaje Quinas:");

        jRadioButtonSena.setText("Puntaje Senas:");

        jRadioButtonGrnd1.setText("Puntaje Grande:");

        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jRadioButtonEsca.setText("Puntaje Escalera:");

        jRadioButtonPoker.setText("Puntaje Poker:");

        jRadioButtonFull.setText("Puntaje Full:");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jRadioButtonGrnd2.setText("Puntaje Grande2:");

        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButtonSave)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonFull)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonGrnd1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonSena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonQuina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonTonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonBala)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonTren)
                                    .addComponent(jRadioButtonCuadra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addContainerGap(100, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonGrnd2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonEsca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonPoker)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBala)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTonto)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTren)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCuadra)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonQuina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonSena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEsca)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPoker)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonFull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonGrnd1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonGrnd2)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        //boton Guardar
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        if(juega1vs1.turnP <= 22){
            System.out.println("turnoPP:" + juega1vs1.turnP);
            if(jRadioButtonBala.isSelected()){     //..............................balas
                //turno jugador 1
                if(juega1vs1.turnP %2 == 0){
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje1.getText().isEmpty()){
                        
                        System.out.println(jLabel1.getText());

                        String nombre1;
                        nombre1 = jLabel1.getText();
                        juega1vs1.jPuntaje1.setText(nombre1);

                        dispose();
                        
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                        System.out.println("turnoP:" + juega1vs1.turnP);
                    }
                  
                //turno jugador 2    
                }else if(juega1vs1.turnP %2 != 0) {
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje11.getText().isEmpty()){
                        
                        System.out.println(jLabel1.getText());

                        String nombre1;
                        nombre1 = jLabel1.getText();
                        juega1vs1.jPuntaje11.setText(nombre1);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                        
                    }
                }
                juega1vs1.turnP++;
                System.out.println("turnoP:" + juega1vs1.turnP);
            }
            if(jRadioButtonTonto.isSelected()){     //..............................tontos
               //turno jugador 1
                if(juega1vs1.turnP % 2 == 0){
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje2.getText().isEmpty()){
                        System.out.println(jLabel2.getText());

                        String nombre2;
                        nombre2 = jLabel2.getText();
                        juega1vs1.jPuntaje2.setText(nombre2);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                //turno jugador 2    
                }else if(juega1vs1.turnP %2 != 0) {
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje22.getText().isEmpty()){
                        
                        System.out.println(jLabel2.getText());

                        String nombre2;
                        nombre2 = jLabel2.getText();
                        juega1vs1.jPuntaje22.setText(nombre2);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--; 
                    }
                }
                juega1vs1.turnP++;
                System.out.println("turnoP:" + juega1vs1.turnP);
            }
            if(jRadioButtonTren.isSelected()){     //..............................trenes
               //turno jugador 1
                if(juega1vs1.turnP % 2 == 0){
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje3.getText().isEmpty()){
                        System.out.println(jLabel3.getText());

                        String nombre3;
                        nombre3 = jLabel3.getText();
                        juega1vs1.jPuntaje3.setText(nombre3);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                //turno jugador 2    
                }else if(juega1vs1.turnP %2 != 0) {
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje33.getText().isEmpty()){
                        System.out.println(jLabel3.getText());

                        String nombre3;
                        nombre3 = jLabel3.getText();
                        juega1vs1.jPuntaje33.setText(nombre3);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                }
                juega1vs1.turnP++;
                System.out.println("turnoP:" + juega1vs1.turnP);
            }
            if(jRadioButtonCuadra.isSelected()){     //..............................cuadras
                //turno jugador 1
                if(juega1vs1.turnP % 2 == 0){
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje4.getText().isEmpty()){
                        System.out.println(jLabel4.getText());

                        String nombre4;
                        nombre4 = jLabel4.getText();
                        juega1vs1.jPuntaje4.setText(nombre4);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                //turno jugador 2    
                }else if(juega1vs1.turnP %2 != 0) {
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje44.getText().isEmpty()){
                        System.out.println(jLabel4.getText());

                        String nombre4;
                        nombre4 = jLabel4.getText();
                        juega1vs1.jPuntaje44.setText(nombre4);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                }
                juega1vs1.turnP++;
                System.out.println("turnoP:" + juega1vs1.turnP);
            }
            if(jRadioButtonQuina.isSelected()){     //..............................quinas
                //turno jugador 1
                if(juega1vs1.turnP % 2 == 0){
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje5.getText().isEmpty()){
                        System.out.println(jLabel5.getText());

                        String nombre5;
                        nombre5 = jLabel5.getText();
                        juega1vs1.jPuntaje5.setText(nombre5);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                //turno jugador 2    
                }else if(juega1vs1.turnP %2 != 0) {
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje55.getText().isEmpty()){
                        System.out.println(jLabel5.getText());

                        String nombre5;
                        nombre5 = jLabel5.getText();
                        juega1vs1.jPuntaje55.setText(nombre5);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                }
                juega1vs1.turnP++;
                System.out.println("turnoP:" + juega1vs1.turnP);
            }
            if(jRadioButtonSena.isSelected()){     //..............................senas
                //turno jugador 1
                if(juega1vs1.turnP % 2 == 0){
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje6.getText().isEmpty()){
                        System.out.println(jLabel6.getText());

                        String nombre6;
                        nombre6 = jLabel6.getText();
                        juega1vs1.jPuntaje6.setText(nombre6);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                //turno jugador 2    
                }else if(juega1vs1.turnP %2 != 0) {
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntaje66.getText().isEmpty()){
                        System.out.println(jLabel6.getText());

                        String nombre6;
                        nombre6 = jLabel6.getText();
                        juega1vs1.jPuntaje66.setText(nombre6);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                }
                juega1vs1.turnP++;
                System.out.println("turnoP:" + juega1vs1.turnP);
            }
            
            if(jRadioButtonGrnd1.isSelected()){     //..............................grande1
                //turno jugador 1
                if(juega1vs1.turnP % 2 == 0){
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntajeG1.getText().isEmpty()){
                        System.out.println(jLabel10.getText());

                        String nombre10;
                        nombre10 = jLabel10.getText();
                        juega1vs1.jPuntajeG1.setText(nombre10);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                //turno jugador 2    
                }else if(juega1vs1.turnP %2 != 0) {
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntajeG12.getText().isEmpty()){
                        System.out.println(jLabel10.getText());

                        String nombre10;
                        nombre10 = jLabel10.getText();
                        juega1vs1.jPuntajeG12.setText(nombre10);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                }
                juega1vs1.turnP++;
                System.out.println("turnoP:" + juega1vs1.turnP);
            }
            //1
            
            if(jRadioButtonGrnd2.isSelected()){     //..............................grande2
                //turno jugador 1
                if(juega1vs1.turnP % 2 == 0){
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntajeG2.getText().isEmpty()){
                        System.out.println(jLabel11.getText());

                        String nombre10;
                        nombre10 = jLabel11.getText();
                        juega1vs1.jPuntajeG2.setText(nombre10);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                //turno jugador 2    
                }else if(juega1vs1.turnP %2 != 0) {
                    if(juega1vs1.jPuntajeG22.getText().isEmpty()){
                        System.out.println(jLabel11.getText());

                        String nombre10;
                        nombre10 = jLabel11.getText();
                        juega1vs1.jPuntajeG22.setText(nombre10);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                }
                juega1vs1.turnP++;
                System.out.println("turnoP:" + juega1vs1.turnP);
            }
            
            //2
            if(jRadioButtonEsca.isSelected()){     //...........................escalera
                //turno jugador 1
                if(juega1vs1.turnP % 2 == 0){
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntajeEs.getText().isEmpty()){
                        System.out.println(jLabel7.getText());

                        String nombre7;
                        nombre7 = jLabel7.getText();
                        juega1vs1.jPuntajeEs.setText(nombre7);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                //turno jugador 2    
                }else if(juega1vs1.turnP %2 != 0) {
                    if(juega1vs1.jPuntajeES2.getText().isEmpty()){
                        System.out.println(jLabel7.getText());

                        String nombre7;
                        nombre7 = jLabel7.getText();
                        juega1vs1.jPuntajeES2.setText(nombre7);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                }
                juega1vs1.turnP++;
                System.out.println("turnoP:" + juega1vs1.turnP);
            }
            if(jRadioButtonFull.isSelected()){        //........................full
                //turno jugador 1
                if(juega1vs1.turnP % 2 == 0){
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntajeFull.getText().isEmpty()){
                        System.out.println(jLabel9.getText());

                        String nombre9;
                        nombre9 = jLabel9.getText();
                        juega1vs1.jPuntajeFull.setText(nombre9);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                //turno jugador 2    
                }else if(juega1vs1.turnP %2 != 0) {
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntajeFull2.getText().isEmpty()){
                        System.out.println(jLabel9.getText());

                        String nombre9;
                        nombre9 = jLabel9.getText();
                        juega1vs1.jPuntajeFull2.setText(nombre9);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                }
                juega1vs1.turnP++;
                System.out.println("turnoP:" + juega1vs1.turnP);
            }
            if(jRadioButtonPoker.isSelected()){     //..........................poker
                //turno jugador 1
                if(juega1vs1.turnP % 2 == 0){
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntajePoker.getText().isEmpty()){
                        System.out.println(jLabel8.getText());

                        String nombre8;
                        nombre8 = jLabel8.getText();
                        juega1vs1.jPuntajePoker.setText(nombre8);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                //turno jugador 2    
                }else if(juega1vs1.turnP %2 != 0) {
                    //condicion si esta vacio -> anotar
                    if(juega1vs1.jPuntajePoker2.getText().isEmpty()){
                        System.out.println(jLabel8.getText());

                        String nombre8;
                        nombre8 = jLabel8.getText();
                        juega1vs1.jPuntajePoker2.setText(nombre8);

                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Puntaje ya establecido");
                        juega1vs1.turnP--;
                    }
                }
                juega1vs1.turnP++;
                System.out.println("turnoP:" + juega1vs1.turnP);
            }  
        }else{
            JOptionPane.showMessageDialog(this,"Fin del Juego");
        }
        //................controla fin del juego
        if(juega1vs1.turno == juega1vs1.turnoS){ 
            JOptionPane.showMessageDialog(this,"Juego Terminado");
            juega1vs1.jBjugar1.setEnabled(false);
            juega1vs1.jBjugar2.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puntajeT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puntajeT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puntajeT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puntajeT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new puntajeT().setVisible(true);
            }
        });
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JButton jButtonSave;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonBala;
    private javax.swing.JRadioButton jRadioButtonCuadra;
    private javax.swing.JRadioButton jRadioButtonEsca;
    private javax.swing.JRadioButton jRadioButtonFull;
    private javax.swing.JRadioButton jRadioButtonGrnd1;
    private javax.swing.JRadioButton jRadioButtonGrnd2;
    private javax.swing.JRadioButton jRadioButtonPoker;
    private javax.swing.JRadioButton jRadioButtonQuina;
    private javax.swing.JRadioButton jRadioButtonSena;
    private javax.swing.JRadioButton jRadioButtonTonto;
    private javax.swing.JRadioButton jRadioButtonTren;
    // End of variables declaration//GEN-END:variables
}
